{
  lib,
  buildPackages,
  mkDerivation,

  illumosSetupHook,
  make,
  install,
  cw,
  yacc,
}:

# illumos' own lex, built out of `usr/src/tools/lex` (a native-build wrapper
# around `usr/src/cmd/sgs/lex`).
#
# Deliberately not called `lex-native`, even though it only ever runs on the
# build host: that is what `nativeBuildInputs` and splicing are for, and it is
# how `make`, `install` and `cw` are already named here. `ld` carries
# its suffix only because a target-platform `sgs-ld` exists alongside it;
# there is no target-side lex in this scope.
#
# `Makefile.master:163` points LEX at `$(ONBLD_TOOLS)/bin/$(MACH)/lex -Y
# $(ONBLD_TOOLS)/share/lib/ccs`, that directory holding the three scanner
# skeletons (`ncform`, `nceucform`, `nrform`), so they are installed next to
# the binary.
#
# flex is not a substitute, and this is why the tool has to be built rather
# than swapped out. In AT&T lex the scanner reads every character through the
# `input()` *macro*, so a scanner over a string just redefines it -- which is
# exactly what `lib/libsec/common/acl_lex.l` does: it `#undef`s `input`/`unput`
# and supplies functions walking the `yybuf` string. flex has no such hook (it
# reads through `YY_INPUT` into its own buffer) and emits `input` as a real
# function, so the two definitions collide outright:
#
#     acl_lex.l:813: error: redefinition of 'input'
#
# Suppressing flex's copy needs `%option noinput`, which AT&T lex does not
# understand, and even then the scanner would be reading from stdin rather
# than from `yybuf`.
#
# lex's own parser is generated by yacc, hence the dependency.
mkDerivation {
  pname = "lex";

  path = "usr/src/tools/lex";
  extraPaths = [
    "usr/src/tools/Makefile.tools"
    "usr/src/tools/Makefile.targ"
    "usr/src/cmd/sgs/lex/common"
    "usr/src/cmd/sgs/include"
    "usr/src/Makefile.master"
    "usr/src/Makefile.native"
    "usr/src/Makefile.smatch"
  ];

  nativeBuildInputs = [
    illumosSetupHook
    make
    install
    cw
    yacc
  ];

  buildFlags = [ "all" ];

  # `Makefile.master`'s YACC names `$(ONBLD_TOOLS)/bin/$(MACH)/yacc`, a proto
  # area that does not exist here. `-P` is not optional: the parser yacc
  # generates `#include`s the skeleton it is pointed at.
  #
  # This has to spell out `buildPackages.illumos.yacc` rather than `${yacc}`.
  # Splicing rewrites `nativeBuildInputs`, not string interpolation, so a bare
  # `${yacc}` names the *target*-platform build -- the same trap documented
  # above `illumosLdWrapper` in mkDerivation.nix. Both spellings appear here on
  # purpose: the argument for the dependency, the explicit path for the string.
  preBuild = ''
    makeFlagsArray+=("YACC=${buildPackages.illumos.yacc}/bin/yacc -P ${buildPackages.illumos.yacc}/share/lib/ccs/yaccpar")
  '';

  # See yacc.nix: upstream's `install` target wants an onbld proto
  # layout keyed on the build host's `uname -p`.
  installPhase = ''
    runHook preInstall

    mkdir -p "$out/bin" "$out/share/lib/ccs"
    cp lex "$out/bin/lex"
    for form in ncform nceucform nrform; do
      cp "$SRC/cmd/sgs/lex/common/$form" "$out/share/lib/ccs/$form"
    done

    runHook postInstall
  '';

  meta.platforms = lib.platforms.unix;
}
