{
  buildPackages,
  mkDerivation,

  illumosSetupHook,
  make,
  install,
  cw,
  ld,

  crt,
  headers,
  libcMinimal,
  libssp_ns,
  libmd,
  libmp,
}:

# libnsl.so.1 -- the "network services library". Despite the name it is not
# just NIS: it carries the whole of TI-RPC and XDR, the TLI/XTI `t_*` transport
# interface, the netdir/netconfig name-to-address machinery, and -- the reason
# most userland wants it -- the `gethostbyname`/`gethostent`/`getrpcent` family
# of resolver entry points. Those are *not* in `libc.so.1`; only the private
# `_so_*` syscall wrappers are.
#
# This is the whole library, all ~180 objects, not a subset. That turned out to
# be the honest option: the RPC, YP and NIS pieces are not separable, because
# `common/mapfile-vers` names every exported symbol and the link runs with
# `-zdefs -zguidance -zfatal-warnings`, so a partial object list fails the link
# rather than quietly shrinking the ABI.
mkDerivation {
  libcMinimal = true;
  path = "usr/src/lib/libnsl/amd64";
  pname = "libnsl-illumos";

  extraPaths = [
    "usr/src/Makefile.master"
    "usr/src/Makefile.master.64"
    "usr/src/Makefile.native"
    "usr/src/Makefile.smatch"

    "usr/src/lib/Makefile.lib"
    "usr/src/lib/Makefile.lib.64"
    "usr/src/lib/Makefile.targ"
    "usr/src/lib/Makefile.rootfs"
    "usr/src/lib/libnsl"

    # ipsec/algs.c includes <ipsec_util.h>, which a full ON build picks up
    # from the proto area (lib/libipsecutil/Makefile installs it into
    # /usr/include). The headers package does not ship it, so include the
    # source directory directly -- the same trick libcMinimal.nix uses for
    # lib/libnvpair.
    "usr/src/lib/libipsecutil"
    # ...which in turn includes <libtecla.h> for the ikeadm CLI. Nothing in
    # algs.c uses it, but the include has to resolve.
    "usr/src/lib/libtecla"

    # nss/gethostby_door.c includes <getxby_door.h>, the nscd door protocol.
    # It is not a public header in the source tree: `lib/libc/Makefile:105`
    # installs it into /usr/include out of `libc/port/gen` as part of libc's
    # `install_h`, and libcMinimal does not run that. Take it from the source
    # directory instead.
    "usr/src/lib/libc/port/gen"

    # Likewise nss/getauuser.c includes <bsm/libbsm.h>, installed into
    # /usr/include/bsm by lib/libbsm's `install_h`. Only the header is used;
    # nothing here links against libbsm.
    "usr/src/lib/libbsm"

    "usr/src/common/mapfiles"
  ];

  nativeBuildInputs = [
    illumosSetupHook
    make
    install
    cw
    ld
    buildPackages.netbsd.rpcgen
    (buildPackages.writeShellScriptBin "arch" "echo i386")
    (buildPackages.writeShellScriptBin "mach" "echo i386")
  ];

  buildInputs = [
    headers
    crt
    libcMinimal
  ];

  env.NIX_CFLAGS_COMPILE = builtins.toString [
    "-B${crt}/lib"
    "-Wno-error"
  ];

  # Same story as head.nix / uts-headers.nix: NetBSD's rpcgen shells out to a
  # C preprocessor, defaults to a /usr/bin path that does not exist here, and
  # it has to be a *traditional* cpp so that `%`-escaped lines pass through
  # without `__STDC__` being expanded inside them.
  env.RPCGEN_CPP = buildPackages.writeShellScript "rpcgen-cpp" ''
    exec ${buildPackages.stdenv.cc}/bin/cpp -traditional-cpp -U__STDC__ "$@"
  '';

  buildFlags = [ "all" ];

  # `nis/gen/nis_clnt.h` is a derived file. Upstream generates it from the
  # *top* libnsl Makefile, which also wants to install `rpcsvc/nis.x` into the
  # proto area first; the headers package already ships both `rpcsvc/nis.x` and
  # `rpcsvc/nis_object.x`, so we can run just the interesting rule here and
  # build `amd64` directly rather than driving the recursive make.
  #
  # The sed pipeline is copied verbatim from `lib/libnsl/Makefile`: rpcgen emits
  # both the protocol definitions (already in `<rpcsvc/nis.h>`) and, after the
  # `EDIT_START` marker, the client-side declarations, which are renamed from
  # rpcgen's `_3`/`_3_svc` version suffixes to `_clnt`/`_svc`.
  preBuild =
    ''
      rpcgen -C -h ${headers}/include/rpcsvc/nis.x > nis_clnt-gen.h
      sed -n -e '/EDIT_START/,$ p' < nis_clnt-gen.h \
        | sed -e 's/_3_svc/_svc/' \
        | sed -e 's/_3/_clnt/' > ../nis/gen/nis_clnt.h
      rm nis_clnt-gen.h
      test -s ../nis/gen/nis_clnt.h

    ''
    # <bsm/libbsm.h> is included with its `bsm/` prefix, so a plain -I at the
    # source directory will not do; stage it under a directory of the right
    # shape.
    + ''
      mkdir -p "$NIX_BUILD_TOP/nsl-include/bsm"
      cp "$SRC/lib/libbsm/common/libbsm.h" "$NIX_BUILD_TOP/nsl-include/bsm/"

    ''
    # <rpc/pmap_prot.h> is generated by rpcgen, and we generate it with
    # NetBSD's rpcgen, which does not implement illumos' K&R output mode.
    # `uts/common/rpc/Makefile:108` runs `$(RPCGEN) -M -h` *without* `-C`, and
    # illumos rpcgen then emits unprototyped `extern bool_t xdr_rmtcallargs();`
    # declarations (rpc_main.c:585, the `if (!Cflag)` arm). NetBSD's rpcgen
    # always emits full ANSI prototypes, so we get
    #
    #     bool_t xdr_rmtcallargs(XDR *, rmtcallargs *);
    #
    # which collides head-on with libnsl's `rpc/pmap_prot.c:177`, whose
    # xdr_rmtcallargs deliberately takes the *client-side* `struct
    # p_rmtcallargs` instead (see the long comment in
    # `uts/common/rpc/pmap_prot.x:159`). `rpcb_prot.h` (generated by the same
    # `-M -h` rule, Makefile:114) has the identical problem with
    # `xdr_rpcb_rmtcallargs` vs `struct r_rpcb_rmtcallargs`.
    #
    # Shadow both headers with copies whose generated declaration block has
    # been converted back to the unprototyped form illumos rpcgen would have
    # emitted -- not deleted, since other translation units (rpc/clnt_bcast.c)
    # do need a declaration to exist. `$NIX_BUILD_TOP/nsl-include` is first on
    # the include path so these win.
    #
    # The real fix belongs in the uts-headers package -- this is a
    # rpcgen-compatibility bug that will bite anything else including these
    # headers -- but that file is owned by another change in flight.
    + ''
      mkdir -p "$NIX_BUILD_TOP/nsl-include/rpc"
      for h in pmap_prot.h rpcb_prot.h; do
        sed -E 's|^bool_t (xdr_[A-Za-z0-9_]+)\(XDR \*.*\);$|extern bool_t \1();|' \
          ${headers}/include/rpc/$h > "$NIX_BUILD_TOP/nsl-include/rpc/$h"
        grep -q 'extern bool_t xdr_' "$NIX_BUILD_TOP/nsl-include/rpc/$h"
      done

    ''
    # See libm.nix: Makefile.lib's default BUILD.SO goes through the compiler
    # driver, which reaches GNU ld via collect2 and dies on -Bdirect.
    #
    # Unlike libm, libnsl needs crti.o/crtn.o spelled out: some of its objects
    # carry .init/.fini sections, and calling $(LD) directly skips the driver's
    # implicit crt objects, so ld warns "symbol '_init' not found, but .init
    # section exists - possible link-edit without using the compiler driver",
    # which -zfatal-warnings (in DYNFLAGS) promotes to an error. Naming them
    # reproduces exactly what the driver would have done.
    + ''
      makeFlagsArray+=("CPPFLAGS.first=-I$NIX_BUILD_TOP/nsl-include -I${headers}/include -I\$(SRC)/lib/libipsecutil/common -I\$(SRC)/lib/libtecla -I\$(SRC)/lib/libc/port/gen")
      makeFlagsArray+=("BUILD.SO=\$(LD) -o \$@ \$(GSHARED) \$(DYNFLAGS) ${crt}/lib/crti.o \$(PICS) \$(EXTPICS) ${crt}/lib/crtn.o -L${libcMinimal}/lib -L${libssp_ns}/lib -L${libmd}/lib -R${libmd}/lib -L${libmp}/lib -R${libmp}/lib \$(LDLIBS)")
    '';

  makeFlags = [
    "MCS=:"
    "POST_PROCESS_O=:"
    "POST_PROCESS_SO=:"
    "LDFLAGS.native="
    "MACH=i386"
    "MACH64=amd64"
    "LD=${
      buildPackages.writeShellScript "illumos-ld" ''
        unset SGS_SUPPORT SGS_SUPPORT_32 SGS_SUPPORT_64
        exec ${buildPackages.illumos.ld}/bin/ld "$@"
      ''
    }"
  ];

  installPhase = ''
    runHook preInstall

    mkdir -p "$out/lib"
    cp libnsl.so.1 "$out/lib/"
    ln -s libnsl.so.1 "$out/lib/libnsl.so"

    runHook postInstall
  '';
}
