{
  mkDerivation,

  crt,
  headers,
  libcMinimal,
  libssp_ns,

  libnsl,
  buildPackages,
  # The DT_NEEDEDs of the above, transitively; the illumos link-editor insists
  # on finding a shared object's dependencies on the link path.
  libmd,
  libmp,
  libsocket,
}:

# librpcsvc.so.1 -- the XDR routines for the standard rpcsvc protocols
# (rstat, rusers, spray, rwall, bootparam, nfs mount).
#
# Packaged because the NFS mount helper links it: cmd/fs.d/nfs/mount has
# `LDLIBS += -lrpcsvc -lnsl -lsocket -lscf`. That helper is what `mount -F nfs`
# dispatches to, and mounting the store from the host is what removes the
# per-build UFS image and the ~986MB copy into RAM at every boot.
#
# Its own objects are almost entirely rpcgen output, which is why this needs
# nothing but libnsl: the protocol definitions live in .x files under
# lib/librpcsvc/common and the derived .c files are generated at build time.
mkDerivation {
  libcMinimal = true;
  illumosLib = true;
  path = "usr/src/lib/librpcsvc/amd64";
  pname = "librpcsvc";

  outputs = [
    "out"
    "dev"
  ];

  extraPaths = [
    "usr/src/lib/Makefile.lib.64"
    "usr/src/lib/Makefile.rootfs"
    "usr/src/lib/librpcsvc"

    # The protocol definitions. librpcsvc is almost entirely rpcgen output and
    # the .x files live in head/rpcsvc, not beside the library.
    "usr/src/head/rpcsvc"

    # nlm_prot.x and sm_inter.x come from the kernel tree, not head/.
    "usr/src/uts/common/rpcsvc"
    "usr/src/uts/common/rpc"

    "usr/src/common/mapfiles"
  ];

  # rpcgen comes from buildPackages.netbsd rather than the illumos scope --
  # this package set has no rpcgen of its own, and head.nix/uts-headers.nix
  # are handed the same one explicitly in default.nix.
  extraNativeBuildInputs = [ buildPackages.netbsd.rpcgen ];

  buildInputs = [
    headers
    crt
    libcMinimal
    libnsl
  ];

  env.NIX_CFLAGS_COMPILE = builtins.toString [
    "-B${crt}/lib"
    "-Wno-error"
  ];

  buildFlags = [ "all" ];

  # NetBSD's rpcgen shells out to a C preprocessor, defaulting to a /usr/bin
  # path that does not exist here. It then emits only boilerplate and still
  # exits 0, so the generated sources come out nearly empty and the failure
  # surfaces much later as missing symbols. It also has to be a *traditional*
  # cpp -- head.nix carries the same warning for the same reason.
  env.RPCGEN_CPP = buildPackages.writeShellScript "rpcgen-cpp" ''
    exec ${buildPackages.stdenv.cc}/bin/cpp -traditional-cpp -U__STDC__ "$@"
  '';

  # The derived .c files are generated by the *top* librpcsvc Makefile
  # (`all: $(DERIVED_FILES) .WAIT $(SUBDIRS)`), and we build the amd64
  # subdirectory directly, so nothing has made them. Ask for them by name
  # before building here; the rules are one level up and read the .x files out
  # of head/rpcsvc.

  # See libm.nix for why BUILD.SO has to invoke $(LD) directly, and libnsl.nix
  # for why crti.o/crtn.o are named explicitly once the compiler driver is out
  # of the picture. Every -L gets a matching -R so the dependency lands in
  # DT_RUNPATH and therefore in the nix closure.
  preBuild = ''
    # The generated .c files say #include "rstat.h" -- unqualified, because
    # upstream generates the header beside them into the proto area. Ours are
    # already installed by the `headers` package, under rpcsvc/, so point at
    # that directory rather than regenerating them.
    makeFlagsArray+=("CPPFLAGS.first=-I${headers}/include -I${headers}/include/rpcsvc")

    make -C .. \
      common/bootparam_prot_xdr.c common/rstat_xdr.c common/rusers_xdr.c \
      common/spray_xdr.c common/nlm_prot.c common/sm_inter_xdr.c \
      common/mount_xdr.c common/nsm_addr_xdr.c common/rpc_sztypes.c

    makeFlagsArray+=("BUILD.SO=\$(LD) -o \$@ \$(GSHARED) \$(DYNFLAGS) ${crt}/lib/crti.o \$(PICS) \$(EXTPICS) ${crt}/lib/crtn.o -L${libcMinimal}/lib -L${libssp_ns}/lib -L${libnsl}/lib -R${libnsl}/lib -L${libmd}/lib -R${libmd}/lib -L${libmp}/lib -R${libmp}/lib -L${libsocket}/lib -R${libsocket}/lib \$(LDLIBS)")
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p "$out/lib"
    cp librpcsvc.so.1 "$out/lib/"
    ln -s librpcsvc.so.1 "$out/lib/librpcsvc.so"

    runHook postInstall
  '';

  meta = {
    description = "illumos XDR routines for the standard rpcsvc protocols";
  };
}
