{
  mkDerivation,

  crt,
  headers,
  libcMinimal,
  libssp_ns,

  libsocket,
  libmd,
  # The DT_NEEDEDs of the above, transitively; the illumos link-editor insists
  # on finding a shared object's dependencies on the link path.
  libnsl,
  libmp,
}:

# libresolv.so.2 -- the BIND 8.2.4 resolver, as imported into illumos under
# usr/src/lib/libresolv2. Provides the `res_*` query interface (`res_nsearch`,
# `res_nquery`, `res_send`, ...), the `ns_*` message parser/printer, the
# `inet_net_*` address conversions, and the IRS name-service switch backends.
#
# libc has none of this: it carries `gethostbyname` and friends via libnsl's
# switch, but not the low-level resolver entry points. Anything that talks DNS
# directly needs -lresolv, and reports the absence as a *missing symbol* rather
# than a missing library -- krb5 stops with
#
#     configure: error: cannot find res_nsearch or res_search
#
# which is what cost curl its GSSAPI support until this was packaged.
#
# Note the declarations are not symmetric in <resolv.h>: `res_nsearch` and the
# rest of the reentrant `res_n*` family are declared unconditionally, while the
# older `res_search`/`res_query` are inside `#ifndef __BIND_NOSTATIC`. A probe
# that only tried the latter under a strict-enough set of feature macros would
# conclude the library is useless while it is in fact right there.
mkDerivation {
  libcMinimal = true;
  illumosLib = true;
  path = "usr/src/lib/libresolv2/amd64";
  pname = "libresolv";

  extraPaths = [
    "usr/src/lib/Makefile.rootfs"
    "usr/src/lib/libresolv2"

    "usr/src/common/mapfiles"
  ];

  buildInputs = [
    headers
    crt
    libcMinimal
    libsocket
    libmd
  ];

  env.NIX_CFLAGS_COMPILE = builtins.toString [
    "-B${crt}/lib"
    "-Wno-error"
  ];

  buildFlags = [ "all" ];

  # lib/libresolv2/include has two *generated* headers, normally produced by
  # the top-level libresolv2 Makefile -- which we do not run, because we build
  # the amd64 subdirectory directly. Both of its generators ask the build host
  # a question whose answer has to be about the target, so neither is usable
  # when cross compiling; write the headers out instead.
  #
  #   os_version.h  make_os_version.sh runs `uname -r` and turns it into
  #                 SUNOS_<ver>/OS_MAJOR/OS_MINOR. On a Linux builder that
  #                 yields the *Linux* kernel release -- SUNOS_6_18_36 and
  #                 OS_MAJOR 6 -- which is not merely unhelpful but actively
  #                 wrong: the sunw_port_before.h feature tests key off it.
  #
  #   port_ipv6.h   probe_ipv6.sh compiles three fragments against the host's
  #                 <netinet/in.h> to decide whether sockaddr_in6/in6_addr
  #                 exist and whether sin6_scope_id is a member. Those are
  #                 compile-only tests, so with the right CC they would give
  #                 the right answer, but the script takes CC/CPPFLAGS from
  #                 the environment and would need the illumos header path
  #                 threaded through it. illumos has all three -- verified in
  #                 <netinet/in.h> -- so state that directly.
  preConfigure = ''
    cat > ../include/os_version.h <<'EOF'
    #ifndef OS_VERSION_H
    #define OS_VERSION_H

    #define SUNOS_5_11
    #define OS_MAJOR 5
    #define OS_MINOR 11

    #endif
    EOF

    cat > ../include/port_ipv6.h <<'EOF'

    /* This file is automatically generated. Do Not Edit. */

    #ifndef port_ipv6_h
    #define port_ipv6_h

    #define HAS_INET6_STRUCTS
    #define HAVE_SIN6_SCOPE_ID

    #endif
    EOF
  '';

  # See libm.nix for why `BUILD.SO` has to be redefined to call `$(LD)`
  # directly, and libnsl.nix for why crti.o/crtn.o have to be named explicitly
  # once the compiler driver is out of the picture. Every `-L` gets a matching
  # `-R`: without it there is no DT_RUNPATH and no nix reference, so the
  # dependency is absent from the closure and never reaches the boot archive.
  #
  # libcMinimal and libssp_ns keep their bare `-L` on purpose -- they are the
  # bootstrap libc, present only so the link resolves, and a RUNPATH to them
  # would pin the minimal libc at run time in place of the composite.
  preBuild = ''
    makeFlagsArray+=("BUILD.SO=\$(LD) -o \$@ \$(GSHARED) \$(DYNFLAGS) ${crt}/lib/crti.o \$(PICS) \$(EXTPICS) ${crt}/lib/crtn.o -L${libcMinimal}/lib -L${libssp_ns}/lib -L${libsocket}/lib -R${libsocket}/lib -L${libnsl}/lib -R${libnsl}/lib -L${libmd}/lib -R${libmd}/lib -L${libmp}/lib -R${libmp}/lib \$(LDLIBS)")
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p "$out/lib"
    cp libresolv.so.2 "$out/lib/"
    ln -s libresolv.so.2 "$out/lib/libresolv.so"

    runHook postInstall
  '';
}
