{
  mkDerivation,
  buildPackages,
  nawk,

  crt,
  headers,
  libcMinimal,
  libssp_ns,
}:

# libsqlite-sys.so -- SQLite *2.8.15*, vendored in the gate at
# usr/src/lib/libsqlite, and the backing store for the SMF repository.
#
# This is emphatically not the system sqlite. illumos carries its own copy and
# renames the library on purpose -- "Make the SO name unlikely to conflict with
# any other libsqlite that might also be found on the system"
# (lib/libsqlite/Makefile.com:11) -- because svc.configd is written against the
# SQLite 2 C API, which is a different API from SQLite 3, not merely an older
# one: `sqlite_open`/`sqlite_exec`/`sqlite_get_table` against `sqlite *`, and
# callback-per-row rather than prepared statements. A nixpkgs sqlite3 cannot
# stand in for it, and the headers land in their own `sqlite-sys` directory
# so that nothing includes the wrong <sqlite.h> by accident. svc.configd's
# Makefile says `-I$(ROOT)/usr/include/sqlite-sys` and `-lsqlite-sys`.
#
# Two build-time wrinkles, both handled below: a parser generator that has to
# run on the *build* host, and no amd64 build directory upstream.
mkDerivation {
  libcMinimal = true;
  illumosLib = true;
  # There is no amd64 directory to point at -- see postPatch.
  path = "usr/src/lib/libsqlite/i386";
  pname = "libsqlite";

  outputs = [
    "out"
    "dev"
  ];

  extraPaths = [
    "usr/src/lib/Makefile.lib.64"
    "usr/src/lib/Makefile.rootfs"
    "usr/src/lib/libsqlite"

    "usr/src/common/mapfiles"
  ];

  buildInputs = [
    headers
    crt
    libcMinimal
  ];

  extraNativeBuildInputs = [
    # The opcodes.h/opcodes.c rules in Makefile.targ scrape src/vdbe.c with
    # `$(AWK)`, and $(AWK) is nawk (Makefile.master:155), not gawk.
    nawk
  ];

  # `lemon`, the parser generator that turns src/parse.y into parse.c, is
  # compiled with $(NATIVECC) and *run* during the build, so it has to be a
  # build-host program. Same arrangement as cw.nix and the ctf tools.
  depsBuildBuild = [ buildPackages.stdenv.cc ];

  env.NIX_CFLAGS_COMPILE = builtins.toString [
    "-B${crt}/lib"
    "-Wno-error"
  ];

  # Two things upstream does elsewhere that have to happen here instead. Paths
  # are relative to the source root: `cdIllumosPath` is itself a postPatch
  # hook, and postPatchHooks run *after* this, so the cd into `path` has not
  # happened yet.
  #
  # First, there is no amd64 build directory to use. lib/libsqlite ships only
  # i386 and sparc, because nothing in the gate has ever needed a 64-bit
  # libsqlite: svc.configd is a 32-bit program upstream. Our userland is
  # amd64-only, so turn the 32-bit leaf directory into the 64-bit one by
  # adding the `Makefile.lib.64` include that every other library's amd64
  # Makefile has. The directory keeps its upstream name and builds amd64
  # objects; that is odd to read, but the alternative is a second copy of the
  # tree, and `path` has to name a directory that already exists because it is
  # also what the source filter rsyncs.
  #
  # Second, sqlite.h is generated by the *top* lib/libsqlite Makefile, which we
  # do not run because we build a leaf directory directly. It is a
  # two-expression sed over src/sqlite.h.in; the values are `SQLITE_VERSION`
  # and `ENCODING` from that Makefile.
  postPatch = ''
    cat > usr/src/lib/libsqlite/i386/Makefile <<'MAKEFILE'
include ../Makefile.com
include ../../Makefile.lib.64

install: all $(ROOTLIBS64) $(ROOTLINKS64)

include ../Makefile.targ
MAKEFILE

    sed -e 's"--VERS--"2.8.15-repcached"' \
        -e s/--ENCODING--/ISO8859/ \
        usr/src/lib/libsqlite/src/sqlite.h.in \
        > usr/src/lib/libsqlite/sqlite.h
  '';

  buildFlags = [ "all" ];

  # `lemon` is built by a recursive `$(MAKE) lemon` from the parse.c rule, so
  # NATIVECC has to survive into that sub-make -- hence passing it as a make
  # *flag* rather than an environment variable. NATIVE_CFLAGS is emptied
  # because it is a Studio-style flag set ($(COPTFLAG) and friends) that a
  # plain host gcc will not accept, and lemon needs no flags at all.
  #
  # See libm.nix for why `BUILD.SO` has to be redefined to call `$(LD)`
  # directly, and libnsl.nix for why crti.o/crtn.o have to be named explicitly
  # once the compiler driver is out of the picture.
  preBuild = ''
    makeFlagsArray+=("NATIVECC=$CC_FOR_BUILD")
    makeFlagsArray+=("NATIVE_CFLAGS=")
    makeFlagsArray+=("BUILD.SO=\$(LD) -o \$@ \$(GSHARED) \$(DYNFLAGS) ${crt}/lib/crti.o \$(PICS) \$(EXTPICS) ${crt}/lib/crtn.o -L${libcMinimal}/lib -L${libssp_ns}/lib \$(LDLIBS)")
  '';

  installPhase =
    ''
      runHook preInstall

      mkdir -p "$out/lib"
      cp libsqlite-sys.so.2.8.15 "$out/lib/"
      ln -s libsqlite-sys.so.2.8.15 "$out/lib/libsqlite-sys.so.1"
      ln -s libsqlite-sys.so.2.8.15 "$out/lib/libsqlite-sys.so"

    ''
    # Under `sqlite-sys/`, because that is the directory svc.configd's
    # Makefile puts on its include path and how the gate keeps this apart
    # from any other sqlite.
    + ''
      mkdir -p "$dev/include/sqlite-sys"
      cp ../sqlite.h ../sqlite-misc.h "$dev/include/sqlite-sys/"

      runHook postInstall
    '';
}
