{
  mkDerivation,

  crt,
  headers,
  libcMinimal,
  libssp_ns,
}:

# libtecla.so.1 -- the command-line editing and completion library. `svccfg`
# links it for its interactive mode: `new_GetLine`/`gl_get_line` is the shell
# prompt you get from a bare `svccfg`, and `gl_customize_completion` is what
# makes tab-completion of FMRIs work.
#
# Built *without* terminfo, which is the interesting part. Upstream compiles
# it `-DUSE_TERMINFO=1 -DHAVE_CURSES_H=1 -DHAVE_TERM_H=1` and links
# `-lcurses`, which would drag in illumos' SVR4 libcurses -- and libcurses is
# a much bigger job than it looks: `curses.h`, `term.h`, `keyname.c`,
# `termcap.c`, `tifget.c`, `tiget.c` and the three `*names.c` capability
# tables are all generated by `ed(1)` scripts run from the top lib/libcurses
# Makefile, `keyname.sh` shells out to ksh's `/usr/bin/print`, and
# `maketerm.ed` relies on SVR4 `ed` mark semantics that GNU `ed` does not
# reproduce ("Invalid address" partway through `maketerm.ed`).
#
# tecla does not need any of it. `getline.c` has three build-time modes --
# terminfo, termcap, and neither -- and the third is not a stub: with neither
# macro defined it fills every capability in from its built-in ANSI/VT100
# strings (the same table it falls back to on a real system when `setupterm`
# fails or `TERM` is unset), and `gl_print_control_sequence` writes the
# sequences out directly instead of through `tputs`. Terminal size still comes
# from `TIOCGWINSZ`, not from the database. The practical difference is
# confined to non-VT100 terminals, which is not a population that will be
# running `svccfg` against a Nix-built illumos.
mkDerivation {
  libcMinimal = true;
  illumosLib = true;
  path = "usr/src/lib/libtecla/amd64";
  pname = "libtecla";

  outputs = [
    "out"
    "dev"
  ];

  extraPaths = [
    "usr/src/lib/Makefile.lib.64"
    "usr/src/lib/Makefile.rootfs"
    "usr/src/lib/libtecla"

    "usr/src/common/mapfiles"
  ];

  buildInputs = [
    headers
    crt
    libcMinimal
  ];

  env.NIX_CFLAGS_COMPILE = builtins.toString [
    "-B${crt}/lib"
    "-Wno-error"
  ];

  buildFlags = [ "all" ];

  # See the header comment. `--replace-fail` on both, so that this stops
  # working loudly rather than silently if upstream rewrites the flags.
  postPatch = ''
    substituteInPlace usr/src/lib/libtecla/Makefile.com \
      --replace-fail '-DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DUSE_TERMINFO=1 -DHAVE_CURSES_H=1 \
	-DHAVE_TERM_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_SELECT=1 \' \
                     '-DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 \
	-DHAVE_SYS_SELECT_H=1 -DHAVE_SELECT=1 \' \
      --replace-fail '$(DYNLIB) :=	LDLIBS += -lcurses' \
                     ""
  '';

  # See libm.nix for why `BUILD.SO` has to be redefined to call `$(LD)`
  # directly, and libnsl.nix for why crti.o/crtn.o have to be named explicitly
  # once the compiler driver is out of the picture.
  preBuild = ''
    makeFlagsArray+=("CPPFLAGS.first=-I${headers}/include -I\$(SRC)/lib/libtecla")
    makeFlagsArray+=("BUILD.SO=\$(LD) -o \$@ \$(GSHARED) \$(DYNFLAGS) ${crt}/lib/crti.o \$(PICS) \$(EXTPICS) ${crt}/lib/crtn.o -L${libcMinimal}/lib -L${libssp_ns}/lib \$(LDLIBS)")
  '';

  # <libtecla.h> sits at the top of lib/libtecla rather than in usr/src/head,
  # and is installed by the top Makefile, which we do not run.
  installPhase = ''
    runHook preInstall

    mkdir -p "$out/lib"
    cp libtecla.so.1 "$out/lib/"
    ln -s libtecla.so.1 "$out/lib/libtecla.so"

    mkdir -p "$dev/include"
    cp ../libtecla.h "$dev/include/"

    runHook postInstall
  '';
}
