{
  buildPackages,
  mkDerivation,

  illumosSetupHook,
  make,
  install,
  cw,
  ld,
  ld-wrapper,
  perl,

  crt,
  headers,
  libcMinimal,
}:

# cmd/sgs/libconv, built for the *target*. This is a static archive of PIC
# objects (LIBRARY = libconv.a, no DYNLIB), linked into ld.so.1, ld(1) and the
# rest of the link-editor family. Nothing is linked here, so libc is only
# needed for its headers -- but the objects are compiled against the target
# libc, hence the libcMinimal stdenv.
mkDerivation {
  libcMinimal = true;
  path = "usr/src/cmd/sgs/libconv/amd64";
  pname = "sgs-libconv";

  extraPaths = [
    "usr/src/Makefile.master"
    "usr/src/Makefile.master.64"
    "usr/src/Makefile.native"
    "usr/src/Makefile.smatch"

    "usr/src/lib/Makefile.lib"
    "usr/src/lib/Makefile.lib.64"
    "usr/src/lib/Makefile.targ"
    "usr/src/lib/Makefile.rootfs"

    "usr/src/cmd/sgs/Makefile.com"
    "usr/src/cmd/sgs/libconv"
    "usr/src/cmd/sgs/include"
    "usr/src/cmd/sgs/messages"
    "usr/src/cmd/sgs/tools"

    "usr/src/common/elfcap"
    "usr/src/common/sgsrtcid"

    "usr/src/lib/libc/inc"
    "usr/src/lib/libdemangle/common"
  ];

  nativeBuildInputs = [
    illumosSetupHook
    make
    install
    cw
    ld
    # report_bufsize.h and the SUNWonld README revision are generated by perl
    # scripts under cmd/sgs/tools.
    perl
    (buildPackages.writeShellScriptBin "arch" "echo i386")
    (buildPackages.writeShellScriptBin "mach" "echo i386")
  ];

  buildInputs = [
    headers
    crt
    libcMinimal
  ];

  env.NIX_CFLAGS_COMPILE = builtins.toString [
    "-B${crt}/lib"
    "-Wno-error"
  ];

  # bld_vernote.ksh is copied to ./bld_vernote and executed via its `#!
  # /usr/bin/ksh` line, which does not exist here. The script only uses
  # constructs bash understands ([[ ]], $(( )), getopts).
  postPatch = ''
    substituteInPlace usr/src/cmd/sgs/libconv/common/bld_vernote.ksh \
      --replace-fail '#! /usr/bin/ksh' '#!${buildPackages.bash}/bin/bash'
  '';

  # libconv/common/demangle.c includes <demangle-sys.h>, which is libdemangle's
  # private header rather than an installed one. $SRC is only known at build
  # time, so this cannot go in env.NIX_CFLAGS_COMPILE.
  preBuild = ''
    export NIX_CFLAGS_COMPILE="$NIX_CFLAGS_COMPILE -I$SRC/lib/libdemangle/common"
  '';

  # Makefile.com:118-122 sets STACKPROTECT = none, because this archive is
  # linked straight into ld.so.1, which runs before libc has set the guard
  # value up. That only clears illumos' own flag; the nixpkgs cc wrapper adds
  # -fstack-protector-strong on top of it. See rtld.nix for what the leftover
  # __stack_chk_fail references do to the ld.so.1 link.
  hardeningDisable = [ "stackprotector" ];

  buildFlags = [ "all" ];

  makeFlags = [
    "MCS=:"
    "POST_PROCESS_O=:"
    "POST_PROCESS_A=:"
    "LDFLAGS.native="
    "CPPFLAGS.first=-I${headers}/include"
    "MACH=i386"
    "MACH64=amd64"
    # $(SGSMSG) is $(ONBLD_TOOLS)/bin/$(MACH)/sgsmsg; ld already builds
    # and installs that, so point at it rather than building sgsmsg again.
    "ONBLD_TOOLS=${buildPackages.illumos.ld}"
    "LD=${ld-wrapper}"
  ];

  # bld_vernote picks its assembler dialect from $MACH, and the amd64 makefile
  # does not export it.
  MACH = "i386";

  installPhase = ''
    runHook preInstall

    mkdir -p "$out/lib"
    cp libconv.a "$out/lib/"

    runHook postInstall
  '';
}
