{
  lib,
  stdenv,
  buildPackages,
  mkDerivation,

  illumosSetupHook,
  make,
  install,
  cw,
  ld,
  ld-wrapper,
  perl,

  crt,
  headers,
  libcMinimal,
  libssp_ns,

  sgs-libconv,
}:

# librtld_db.so.1 -- the runtime linker debugging interface. It lets a
# controlling process (a debugger, or anything using libproc) walk another
# process's ld.so.1 state: the link map, object load addresses, and PLT
# resolution, so that a breakpoint can be set on a not-yet-resolved PLT entry.
#
# It is here because `libproc` links `-lrtld_db`, and the chain to
# `svc.startd` runs libproc -> libproject -> librestart -> startd.
#
# Built out of cmd/sgs like the rest of the link-editor family, so it follows
# sgs-libconv.nix rather than the `illumosLib` pattern: `msg.c`/`msg.h` are
# generated by `sgsmsg` from ../common/librtld_db.msg, which is why
# `ONBLD_TOOLS` points at the `ld` package that already builds and installs
# that tool.
mkDerivation {
  libcMinimal = true;
  path = "usr/src/cmd/sgs/librtld_db/amd64";

  # Its makefiles index source, object or install directories by $(MACH) /
  # $(MACH64), so it needs the illumos spelling of the CPU. Not the default:
  # setting MACH for a package whose install rules do not expect it relocates
  # that package's output. See `machMakeFlags` in mkDerivation.nix.
  illumosMach = true;
  pname = "sgs-librtld_db";

  extraPaths = [
    "usr/src/Makefile.master"
    "usr/src/Makefile.master.64"
    "usr/src/Makefile.native"
    "usr/src/Makefile.smatch"

    "usr/src/lib/Makefile.lib"
    "usr/src/lib/Makefile.lib.64"
    "usr/src/lib/Makefile.targ"
    "usr/src/lib/Makefile.rootfs"

    "usr/src/cmd/sgs/Makefile.com"
    "usr/src/cmd/sgs/librtld_db"
    "usr/src/cmd/sgs/include"
    "usr/src/cmd/sgs/messages"
    "usr/src/cmd/sgs/tools"

    "usr/src/common/elfcap"
    "usr/src/common/sgsrtcid"

    "usr/src/lib/libc/inc"

    "usr/src/common/mapfiles"
  ];

  nativeBuildInputs = [
    illumosSetupHook
    make
    install
    cw
    ld
    # report_bufsize.h and the SUNWonld README revision are generated by perl
    # scripts under cmd/sgs/tools.
    perl
    (buildPackages.writeShellScriptBin "arch" "echo i386")
    (buildPackages.writeShellScriptBin "mach" "echo i386")
  ];

  buildInputs = lib.optionals stdenv.hostPlatform.isIllumos [
    headers
    crt
    libcMinimal
  ];

  env.NIX_CFLAGS_COMPILE = builtins.toString [
    "-B${crt}/lib"
    "-Wno-error"
  ];

  buildFlags = [ "all" ];

  # `CONVLIBDIR` is `-L$(SGSHOME)/libconv/$(MACH64)`, i.e. the sibling build
  # directory in a full gate build. We build one leaf at a time, so point it
  # at the packaged archive instead.
  #
  # See libm.nix for why `BUILD.SO` has to be redefined to call `$(LD)`
  # directly, and libnsl.nix for why crti.o/crtn.o have to be named
  # explicitly once the compiler driver is out of the picture.
  preBuild = ''
    makeFlagsArray+=("CONVLIBDIR=-L${sgs-libconv}/lib")
    makeFlagsArray+=("BUILD.SO=\$(LD) -o \$@ \$(GSHARED) \$(DYNFLAGS) ${crt}/lib/crti.o \$(PICS) \$(EXTPICS) ${crt}/lib/crtn.o -L${libcMinimal}/lib -L${libssp_ns}/lib -L${sgs-libconv}/lib \$(LDLIBS)")
  '';

  makeFlags = [
    "MCS=:"
    "POST_PROCESS_O=:"
    "POST_PROCESS_SO=:"
    "LDFLAGS.native="
    "CPPFLAGS.first=-I${headers}/include"
    # $(SGSMSG) is $(ONBLD_TOOLS)/bin/$(MACH)/sgsmsg. `ld` used to build and
    # install sgsmsg as a by-product of the `tools/sgs` aggregate, but it is
    # built from `cmd/sgs/ld` now and no longer ships it, so name the `sgsmsg`
    # package directly. `buildPackages.illumos.` because sgsmsg runs during
    # this build; the target instance would need libc and recurse.
    "SGSMSG=${buildPackages.illumos.sgsmsg}/bin/sgsmsg"
    "LD=${ld-wrapper}"
  ];

  MACH = "i386";

  # <rtld_db.h> lives in usr/src/head and is already shipped by the `headers`
  # package, so there is nothing to install but the library itself.
  installPhase = ''
    runHook preInstall

    mkdir -p "$out/lib"
    cp librtld_db.so.1 "$out/lib/"
    ln -s librtld_db.so.1 "$out/lib/librtld_db.so"

    runHook postInstall
  '';

  meta = {
    platforms = lib.platforms.unix;
  };
}
