{
  lib,
  stdenv,
  buildPackages,
  mkDerivation,

  illumosSetupHook,
  make,
  install,
  cw,
  ld,
  ld-wrapper,
  perl,

  libcompat,
  sgsmsg,

  crt,
  headers,
  libcMinimal,
}:

# cmd/sgs/libconv, built for the *target*. This is a static archive of PIC
# objects (LIBRARY = libconv.a, no DYNLIB), linked into ld.so.1, ld(1) and the
# rest of the link-editor family. Nothing is linked here, so libc is only
# needed for its headers -- but the objects are compiled against the target
# libc, hence the libcMinimal stdenv.
let
  forIllumos = stdenv.hostPlatform.isIllumos;
in

mkDerivation {
  libcMinimal = forIllumos;

  # For the target, cmd/sgs/libconv built against the target libc. For the
  # build platform, tools/sgs/libconv: the gate's own native arm, which trims
  # the archive to what ld(1) calls (no corenote, no lddstub, no vernote.o) and
  # adds back link_ver_string, assfail() and panic() from $(COMPAT_SUPPORT_SRC).
  path = if forIllumos then "usr/src/cmd/sgs/libconv/amd64" else "usr/src/tools/sgs/libconv";
  pname = "sgs-libconv";

  extraPaths = [
    "usr/src/Makefile.master"
    "usr/src/Makefile.master.64"
    "usr/src/Makefile.native"
    "usr/src/Makefile.smatch"

    "usr/src/lib/Makefile.lib"
    "usr/src/lib/Makefile.lib.64"
    "usr/src/lib/Makefile.targ"
    "usr/src/lib/Makefile.rootfs"

    "usr/src/cmd/sgs/Makefile.com"
    "usr/src/cmd/sgs/libconv"
    "usr/src/cmd/sgs/include"
    "usr/src/cmd/sgs/messages"
    "usr/src/cmd/sgs/tools"

    "usr/src/common/elfcap"
    "usr/src/common/sgsrtcid"

    "usr/src/lib/libc/inc"
    "usr/src/lib/libdemangle/common"
  ]
  ++ lib.optionals (!forIllumos) [
    # tools/sgs/libconv/Makefile includes ../../Makefile.tools, ../Makefile.com
    # and $(SRC)/cmd/sgs/libconv/Makefile.com; assfail.c comes from
    # $(SGSCOMMON), which is cmd/sgs/common.
    "usr/src/tools/Makefile.tools"
    "usr/src/tools/Makefile.targ"
    "usr/src/tools/sgs/Makefile.com"
    "usr/src/cmd/sgs/common"
  ];

  nativeBuildInputs = [
    illumosSetupHook
    make
    install
    cw
  ]
  ++ lib.optionals forIllumos [ ld ]
  ++ [
    # report_bufsize.h and the SUNWonld README revision are generated by perl
    # scripts under cmd/sgs/tools.
    perl
    (buildPackages.writeShellScriptBin "arch" "echo i386")
    (buildPackages.writeShellScriptBin "mach" "echo i386")
  ];

  buildInputs = lib.optionals stdenv.hostPlatform.isIllumos [
    headers
    crt
    libcMinimal
  ];

  # -Wno-error applies to both arms. On the build platform illumos' own
  # <sys/elf_amd64.h> and glibc's <elf.h> both define SHT_X86_64_UNWIND, to the
  # same value; the redefinition warning is benign and would otherwise be fatal.
  env.NIX_CFLAGS_COMPILE = builtins.toString (
    lib.optional forIllumos "-B${crt}/lib" ++ [ "-Wno-error" ]
  );

  # bld_vernote.ksh is copied to ./bld_vernote and executed via its `#!
  # /usr/bin/ksh` line, which does not exist here. The script only uses
  # constructs bash understands ([[ ]], $(( )), getopts).
  postPatch = ''
    substituteInPlace usr/src/cmd/sgs/libconv/common/bld_vernote.ksh \
      --replace-fail '#! /usr/bin/ksh' '#!${buildPackages.bash}/bin/bash'
  '';

  # libconv/common/demangle.c includes <demangle-sys.h>, which is libdemangle's
  # private header rather than an installed one. $SRC is only known at build
  # time, so this cannot go in env.NIX_CFLAGS_COMPILE.
  preBuild = ''
    export NIX_CFLAGS_COMPILE="$NIX_CFLAGS_COMPILE -I$SRC/lib/libdemangle/common"
  '';

  # Makefile.com:118-122 sets STACKPROTECT = none, because this archive is
  # linked straight into ld.so.1, which runs before libc has set the guard
  # value up. That only clears illumos' own flag; the nixpkgs cc wrapper adds
  # -fstack-protector-strong on top of it. See rtld.nix for what the leftover
  # __stack_chk_fail references do to the ld.so.1 link.
  hardeningDisable = [ "stackprotector" ];

  buildFlags = [ "all" ];

  makeFlags = [
    "MCS=:"
    "POST_PROCESS_O=:"
    "POST_PROCESS_A=:"
    "LDFLAGS.native="

    # $(SGSMSG) is $(ONBLD_TOOLS)/bin/$(MACH)/sgsmsg (cmd/sgs/Makefile.com:110).
    # sgsmsg is its own package, so name the binary rather than rebuilding the
    # onbld bin/$(MACH) layout around it.
    "SGSMSG=${sgsmsg}/bin/sgsmsg"
  ]
  ++ lib.optionals forIllumos [
    "CPPFLAGS.first=-I${headers}/include"
    "LD=${ld-wrapper}"
  ]
  ++ lib.optionals (!forIllumos) [
    # libcompat, built rather than compiled again out of the gate tree.
    # tools/sgs/libconv compiles $(COMPAT_SUPPORT_SRC) into native_support.o
    # for link_ver_string, assfail3() and panic().
    "COMPAT_DIR=${libcompat}/include-native"
    "COMPAT_INC=${libcompat}/include"
  ];

  # bld_vernote picks its assembler dialect from $MACH, and the amd64 makefile
  # does not export it.
  MACH = "i386";

  installPhase = ''
    runHook preInstall

    mkdir -p "$out/lib"
    cp libconv.a "$out/lib/"

    runHook postInstall
  '';

  meta = {
    platforms = lib.platforms.unix;
  };
}
