{
  lib,
  mkDerivation,

  cw,
  onbld-native,
  buildPackages,
}:

# vtfontcvt(1ONBLD): converts a BDF console font into C source. `unix` needs it
# -- FONT_OBJS is part of BOOT_DRIVER_OBJS and so of CORE_OBJS
# (uts/i86pc/Makefile.files:158), generated by the rule at
# uts/i86pc/Makefile.rules:254.
#
# A build-host program, so `noCC` plus the host compiler via `depsBuildBuild`;
# see pkgs/libdwarf.nix.
mkDerivation {
  pname = "vtfontcvt";
  noCC = true;

  path = "usr/src/tools/vtfontcvt";
  extraPaths = [
    "usr/src/Makefile.master"
    "usr/src/Makefile.master.64"
    "usr/src/Makefile.native"
    "usr/src/Makefile.smatch"

    "usr/src/tools/Makefile.tools"
    "usr/src/tools/Makefile.targ"

    "usr/src/cmd/vtfontcvt"
    # cmd/vtfontcvt/Makefile.common:21 compiles the in-gate lz4 alongside it.
    "usr/src/common/lz4"
  ];

  makeFlags = [
    "ROOTONBLD=${builtins.placeholder "out"}"
    "MACH=i386"
    "MACH64=amd64"

    # See elfextract.nix for both of these.
    "NATIVE_MACH=amd64"
    "LDCHECKS="

    # POST_PROCESS ends in $(STRIP_STABS), i.e. `$(STRIP) -x $@`
    # (Makefile.master:979). STRIP is undefined for a `noCC` derivation, so the
    # recipe degenerates to running `-x` as a command. These are build tools,
    # not deliverables, and nothing needs them stripped; tools/sgs/Makefile.com
    # neutralises the same macro.
    "STRIP_STABS=:"

    # Makefile.master:150 spells the installer `install`, which on a Linux
    # build host is coreutils' and does not take -f. illumos' own is
    # install.bin; tools/ctf/Makefile.ctf.native redirects it the same way.
    "INS=install.bin"

    # cmd/vtfontcvt/Makefile.common:28 links against libumem, illumos' slab
    # allocator. vtfontcvt.c only ever calls malloc/free -- the dependency is
    # inherited boilerplate -- so drop it rather than port libumem.
    "LDLIBS="
  ];

  buildFlags = [ "install" ];
  dontInstall = true;

  extraNativeBuildInputs = [ cw ];

  depsBuildBuild = [ buildPackages.stdenv.cc ];

  preBuild = ''
    mkdir -p $out/bin/i386

    # Drop the `CPPFLAGS += -I../../uts/common` its Makefile adds -- see the
    # same note in mbh-patch.nix -- while keeping the in-gate lz4 headers it
    # also adds there. This goes through makeFlagsArray rather than makeFlags
    # because the value contains a space.
    makeFlagsArray+=("CPPFLAGS=-D_TS_ERRNO -I$SRC/common/lz4")

    export NIX_CFLAGS_COMPILE_FOR_BUILD="$NIX_CFLAGS_COMPILE_FOR_BUILD -I${onbld-native}/include -include ${onbld-native}/include/native_compat.h"
  '';

  postFixup = ''
    ln -s i386/vtfontcvt $out/bin/vtfontcvt
  '';

  meta.platforms = lib.platforms.unix;
}
