{
  lib,
  mkDerivation,

  cw,
  compat,
}:

# vtfontcvt(1ONBLD): converts a BDF console font into C source. `unix` needs it
# -- FONT_OBJS is part of BOOT_DRIVER_OBJS and so of CORE_OBJS
# (uts/i86pc/Makefile.files:158), generated by the rule at
# uts/i86pc/Makefile.rules:254.
#
# A build-host program. Nothing here needs to say so: the illumos scope splices
# (`makeScopeWithSplicing'`), so a `nativeBuildInputs` entry already resolves to
# the build-platform instance, and mkDerivation derives the native-build overlay
# from the platforms.
# see pkgs/libdwarf.nix.
mkDerivation {
  pname = "vtfontcvt";

  path = "usr/src/tools/vtfontcvt";
  extraPaths = [
    "usr/src/Makefile.master"
    "usr/src/Makefile.master.64"
    "usr/src/Makefile.native"
    "usr/src/Makefile.smatch"

    "usr/src/tools/Makefile.tools"
    "usr/src/tools/Makefile.targ"

    "usr/src/cmd/vtfontcvt"
    # cmd/vtfontcvt/Makefile.common:21 compiles the in-gate lz4 alongside it.
    "usr/src/common/lz4"
  ];

  # Installs into, or reads from, the onbld $(ROOTONBLD)/bin/$(MACH) layout,
  # so it needs MACH set even when it is built for the build host.
  illumosOnbldMach = true;

  makeFlags = [
    "ROOTONBLD=${builtins.placeholder "out"}"

    # LDCHECKS and STRIP_STABS used to be restated here too; both now come
    # from mkDerivation's build-host overlay.

    # Makefile.master:150 spells the installer `install`, which on a Linux
    # build host is coreutils' and does not take -f. illumos' own is
    # install.bin; tools/ctf/Makefile.ctf.native redirects it the same way.
    "INS=install.bin"

    # cmd/vtfontcvt/Makefile.common:28 links against libumem, illumos' slab
    # allocator. vtfontcvt.c only ever calls malloc/free -- the dependency is
    # inherited boilerplate -- so drop it rather than port libumem.
    "LDLIBS="
  ];

  buildFlags = [ "install" ];
  dontInstall = true;

  extraNativeBuildInputs = [ cw ];

  preBuild = ''
    mkdir -p $out/bin/i386

    # Drop the `CPPFLAGS += -I../../uts/common` its Makefile adds -- see the
    # same note in mbh-patch.nix -- while keeping the in-gate lz4 headers it
    # also adds there. This goes through makeFlagsArray rather than makeFlags
    # because the value contains a space.
    makeFlagsArray+=("CPPFLAGS=-D_TS_ERRNO -I$SRC/common/lz4")

    export NIX_CFLAGS_COMPILE="$NIX_CFLAGS_COMPILE ${compat.stagedCflags}"
  '';

  postFixup = ''
    ln -s i386/vtfontcvt $out/bin/vtfontcvt
  '';

  meta.platforms = lib.platforms.unix;
}
