{
  fetchurl,
  lib,
  stdenv,
  libiconv,
  libunistring,
  help2man,
  texinfo,
  buildPackages,
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

stdenv.mkDerivation rec {
  pname = "libidn2";
  version = "2.3.8";

  src = fetchurl {
    url = "https://ftp.gnu.org/gnu/libidn/libidn2-${version}.tar.gz";
    hash = "sha256-9VeRG/YXFiHh9y/zX1sYJbs1tS7UUyXc3ukx5dPAeHo=";
  };

  strictDeps = true;
  # Beware: non-bootstrap libidn2 is overridden by ./hack.nix
  outputs = [
    "bin"
    "dev"
    "out"
    "info"
    "devdoc"
  ];

  enableParallelBuilding = true;

  # The above patch causes the documentation to be regenerated, so the
  # documentation tools are required.
  nativeBuildInputs = lib.optionals stdenv.hostPlatform.isDarwin [
    help2man
    texinfo
  ];
  buildInputs = [ libunistring ] ++ lib.optional stdenv.hostPlatform.isDarwin libiconv;
  depsBuildBuild = [ buildPackages.stdenv.cc ];

  # gnulib decides whether MB_CUR_MAX needs replacing by *running* a test
  # program, so cross compiling only ever gets to guess -- and it guesses "no",
  # i.e. "broken". That makes gnulib emit its own `gl_MB_CUR_MAX` as an extern
  # inline in the generated stdlib.h, which both gl/ and unistring/ then define,
  # and since gcc 10 defaults to -fno-common the two collide at link time:
  #
  #   libgnu.a(libgnu_la-stdlib.o): multiple definition of `gl_MB_CUR_MAX';
  #   libunistring.a(libunistring_la-stdlib.o): first defined here
  #
  # illumos' MB_CUR_MAX is fine, so answer the probe instead of guessing.
  env = lib.optionalAttrs stdenv.hostPlatform.isSunOS {
    gl_cv_macro_MB_CUR_MAX_good = "yes";
  };

  meta = {
    homepage = "https://www.gnu.org/software/libidn/#libidn2";
    description = "Free software implementation of IDNA2008 and TR46";

    longDescription = ''
      Libidn2 is believed to be a complete IDNA2008 and TR46 implementation,
      but has yet to be as extensively used as the IDNA2003 Libidn library.

      The installed C library libidn2 is dual-licensed under LGPLv3+|GPLv2+,
      while the rest of the package is GPLv3+.  See the file COPYING for
      detailed information.
    '';

    mainProgram = "idn2";
    license = with lib.licenses; [
      lgpl3Plus
      gpl2Plus
      gpl3Plus
    ];
    platforms = lib.platforms.all;
    maintainers = with lib.maintainers; [ fpletz ];
    identifiers.cpeParts = lib.meta.cpeFullVersionWithVendor "gnu" version;
  };
}
